import = [
    "~/.config/alacritty/themes/alacritty-theme/themes/github_dark_default.toml"
]

[font]
size=13.0

[font.normal]
family="SF Mono"
style="Regular"

[font.bold]
family="SF Mono"
style="Regular"

[font.italic]
family="SF Mono"
style="Italic"

[font.bold_italic]
family="SF Mono"
style="Italic"

[window]
dynamic_padding=false
opacity=1.0

[window.padding]
x=12
y=12
