#
#
# @file ~/.config/alacritty/alacritty.toml
# @brief Configuration file for Alacritty.

[font]
size = 13.0

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

[window]
#dynamic_padding = false
opacity = 0.6

[window.padding]
x = 6
y = 6
