import=[
    "~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_dark.toml"
]

[font]
size=11.0

[font.normal]
family="FiraCode Nerd Font"
style="Regular"

[font.bold]
family="FiraCode Nerd Font"
style="Regular"

[font.italic]
family="FiraCode Nerd Font"
style="Italic"

[font.bold_italic]
family="FiraCode Nerd Font"
style="Italic"

[cursor]
blink_interval=200
blink_timeout=0
thickness=0.20

[cursor.style]
shape="Underline"
blinking="On"

[window]
dynamic_padding=false
opacity=1.0

[window.padding]
x=0
y=0
