#
# ~/.config/alacritty/alacritty.toml
#

# See https://alacritty.org/config-alacritty.html

import=["~/.config/alacritty/themes/alacritty-theme/themes/github_dark_default.toml",]

# ========== Environment variables ==========
[env]
TERM="xterm-256color"

# ========== Window ==========
[window]
#dimensions={columns=0,lines=0}
padding={x=12,y=12}
dynamic_padding=false
opacity=0.8
#decorations_theme_variant="None"

# ========== Scrolling ==========
[scrolling]
#history=10000
#multiplier=3

# ========== Font ==========
[font]
normal={family="SF Mono",style="Regular"}
bold={family="SF Mono",style="Regular"}
italic={family="SF Mono",style="Regular"}
bold_italic={family="SF Mono",style="Regular"}
size=11.0
#offset={x=0,y=0}
#glyph_offset={x=0,y=0}
#builtin_box_drawing=true

# ========== Cursor ==========
[cursor]
style={shape="Underline",blinking="On"}
blink_interval=200
blink_timeout=0
unfocused_hollow=false
thickness=0.20
