# Alacritty Configuration File
# ~/.config/alacritty/alacritty.toml
#
# For more information on configuring Alacritty, visit: https://alacritty.org/config-alacritty.html

#import = [
#    "~/.config/alacritty/themes/rose-pine.toml",
#]

live_config_reload = true

[env]
#TERM = "xterm-256color"

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 1.0

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Regular" }
italic = { family = "FiraCode Nerd Font", style = "Regular" }
bold_italic = { family = "FiraCode Nerd Font", style = "Regular" }
size = 11.25

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 200
blink_timeout = 0
unfocused_hollow = false
thickness = 0.20
