# Alacritty Configuration File
# ~/.config/alacritty/alacritty.toml
#
# For more information on configuring Alacritty, visit: https://alacritty.org/config-alacritty.html

# Import additional configuration files if needed
import = [
    "~/.config/alacritty/themes/rose-pine.toml",
]

# Environment Variables
[env]
    TERM = "xterm-256color"

# Window Settings
[window]
    # Padding around the window in pixels
    padding = { x = 12, y = 12 }
    # Background opacity as a floating point number from 0.0 to 1.0
    opacity = 1.0

# Font Settings
[font]
    # Font settings for normal, bold, italic, and bold italic styles
    normal = { family = "monospace", style = "Regular" }
    bold = { family = "monospace", style = "Regular" }
    italic = { family = "monospace", style = "Regular" }
    bold_italic = { family = "monospace", style = "Regular" }
    # Font size in points
    size = 11.25

# Cursor Settings
[cursor]
    # Cursor style: "Block", "Underline", or "Beam"
    style = { shape = "Underline", blinking = "On" }
    # Cursor blinking interval in milliseconds
    blink_interval = 200
    # Time after which cursor stops blinking, in seconds
    blink_timeout = 0
    # Render cursor as a hollow box when the window is not focused
    unfocused_hollow = false
    # Thickness of the cursor relative to the cell width
    thickness = 0.20
