import = [
    "~/.config/alacritty/themes/gruvbox.toml",
]

live_config_reload = true

[env]
#TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = false
opacity = 1.0

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Regular" }
italic = { family = "monospace", style = "Regular" }
bold_italic = { family = "monospace", style = "Regular" }
size = 11.25

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 200
blink_timeout = 0
unfocused_hollow = false
thickness = 0.20
